namespace FatooraRahatak.Application.DTOs.Accounting;

public class JournalEntryLineDto
{
    public long Id { get; set; }
    public long AccountId { get; set; }
    public string AccountCode { get; set; } = string.Empty;
    public string AccountNameAr { get; set; } = string.Empty;
    public decimal Debit { get; set; }
    public decimal Credit { get; set; }
    public string? LineDescription { get; set; }
}

public class JournalEntryDto
{
    public long Id { get; set; }
    public string EntryNumber { get; set; } = string.Empty;
    public DateOnly EntryDate { get; set; }
    public string? Description { get; set; }
    public string Status { get; set; } = string.Empty;
    public long CreatedByUserId { get; set; }
    public string CreatedByName { get; set; } = string.Empty;
    public long? ApprovedByUserId { get; set; }
    public string? ApprovedByName { get; set; }
    public long? ReversalOfEntryId { get; set; }
    public bool IsAutoGenerated { get; set; }
    public string? SourceType { get; set; }
    public decimal TotalDebit { get; set; }
    public decimal TotalCredit { get; set; }
    public List<JournalEntryLineDto> Lines { get; set; } = new();
}