"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { useTranslation } from "react-i18next";
import "@/lib/i18n/config";
import api from "@/lib/api";
import { getUserType } from "@/lib/auth";
import Icon from "@/components/Icon";
import LoadingState from "@/components/LoadingState";

interface JournalEntryLine {
  id: number;
  accountId: number;
  accountCode: string;
  accountNameAr: string;
  debit: number;
  credit: number;
  lineDescription: string | null;
}

interface JournalEntry {
  id: number;
  entryNumber: string;
  entryDate: string;
  description: string | null;
  status: string;
  createdByUserId: number;
  createdByName: string;
  approvedByUserId: number | null;
  approvedByName: string | null;
  reversalOfEntryId: number | null;
  isAutoGenerated: boolean;
  sourceType: string | null;
  totalDebit: number;
  totalCredit: number;
  lines: JournalEntryLine[];
}

const statusLabels: Record<string, string> = {
  PendingApproval: "journalEntry.statusPending",
  Approved: "journalEntry.statusApproved",
  Rejected: "journalEntry.statusRejected",
  Reversed: "journalEntry.statusReversed",
};

const statusStyles: Record<string, string> = {
  PendingApproval: "badge badge--yellow",
  Approved: "badge badge--green",
  Rejected: "badge badge--red",
  Reversed: "badge badge--gray",
};

export default function JournalEntryDetailPage() {
  const { t } = useTranslation();
  const params = useParams();
  const router = useRouter();
  const id = params?.id as string;

  const [entry, setEntry] = useState<JournalEntry | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [actionError, setActionError] = useState("");
  const [successMessage, setSuccessMessage] = useState("");
  const [actionLoading, setActionLoading] = useState(false);
  const [userType, setUserType] = useState<string | null>(null);

  useEffect(() => {
    setUserType(getUserType());
  }, []);

  const fetchEntry = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const res = await api.get(`/journal-entries/${id}`);
      setEntry(res.data.data);
    } catch (err: any) {
      setError(err.response?.data?.message || t("journalEntry.loadDetailError"));
    } finally {
      setLoading(false);
    }
  }, [id, t]);

  useEffect(() => {
    if (id) fetchEntry();
  }, [id, fetchEntry]);

  const isOwner = userType === "Owner";

  const handleApprove = async () => {
    setActionError("");
    setSuccessMessage("");
    setActionLoading(true);
    try {
      await api.put(`/journal-entries/${id}/approve`);
      setSuccessMessage(t("journalEntry.approveSuccess"));
      await fetchEntry();
    } catch (err: any) {
      setActionError(err.response?.data?.message || t("journalEntry.approveError"));
    } finally {
      setActionLoading(false);
    }
  };

  const handleReject = async () => {
    if (!window.confirm(t("journalEntry.rejectConfirm"))) return;
    setActionError("");
    setSuccessMessage("");
    setActionLoading(true);
    try {
      await api.put(`/journal-entries/${id}/reject`);
      setSuccessMessage(t("journalEntry.rejectSuccess"));
      await fetchEntry();
    } catch (err: any) {
      setActionError(err.response?.data?.message || t("journalEntry.rejectError"));
    } finally {
      setActionLoading(false);
    }
  };

  const handleReverse = async () => {
    if (!window.confirm(t("journalEntry.reverseConfirm"))) return;
    setActionError("");
    setSuccessMessage("");
    setActionLoading(true);
    try {
      const res = await api.post(`/journal-entries/${id}/reverse`);
      setSuccessMessage(t("journalEntry.reverseSuccess"));
      router.push(`/dashboard/accounting/journal-entries/${res.data.data.id}`);
    } catch (err: any) {
      setActionError(err.response?.data?.message || t("journalEntry.reverseError"));
    } finally {
      setActionLoading(false);
    }
  };

  if (loading) {
    return <LoadingState />;
  }

  if (error || !entry) {
    return (
      <div>
        <div className="alert alert--danger">
          {error || t("journalEntry.notFound")}
        </div>
        <Link href="/dashboard/accounting/journal-entries" className="text-[var(--blue)] text-sm mt-3 inline-block hover:underline">
          {t("journalEntry.backToList")}
        </Link>
      </div>
    );
  }

  return (
    <div>
      <Link
        href="/dashboard/accounting/journal-entries"
        className="flex items-center gap-1.5 text-[13px] text-[var(--sub)] hover:text-[var(--ink)] mb-4"
      >
        <Icon name="arrowLeft" />
        {t("journalEntry.backToListFull")}
      </Link>

      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <h1 className="text-[22px] font-bold text-[var(--blue-deep)]" dir="ltr">
            {entry.entryNumber}
          </h1>
          <span className={statusStyles[entry.status] ?? "badge badge--gray"}>
            {t(statusLabels[entry.status] ?? "common.noData")}
          </span>
        </div>

        {isOwner && (
          <div className="flex gap-2">
            {entry.status === "PendingApproval" && (
              <>
                <button
                  onClick={handleApprove}
                  disabled={actionLoading}
                  className="btn btn-primary disabled:opacity-60 flex items-center gap-1.5"
                >
                  <Icon name="check" />
                  {t("journalEntry.approve")}
                </button>
                <button
                  onClick={handleReject}
                  disabled={actionLoading}
                  className="btn btn-danger disabled:opacity-60 flex items-center gap-1.5"
                >
                  <Icon name="close" />
                  {t("journalEntry.reject")}
                </button>
              </>
            )}
            {entry.status === "Approved" && (
              <button
                onClick={handleReverse}
                disabled={actionLoading}
                className="btn btn-secondary disabled:opacity-60 flex items-center gap-1.5"
              >
                <svg viewBox="0 0 24 24" fill="none" width="16" height="16">
                  <path d="M9 14 4 9l5-5M4 9h11a4 4 0 0 1 4 4v1" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
                </svg>
                {t("journalEntry.reverse")}
              </button>
            )}
          </div>
        )}
      </div>

      {actionError && <div className="alert alert--danger mb-4">{actionError}</div>}

      {successMessage && <div className="alert alert--success mb-4">{successMessage}</div>}

      {entry.reversalOfEntryId && (
        <div className="bg-[var(--blue-50)] text-[var(--blue-deep)] rounded-xl p-4 mb-4 text-sm">
          {t("journalEntry.reversalOf")}{" "}
          <Link href={`/dashboard/accounting/journal-entries/${entry.reversalOfEntryId}`} className="font-bold hover:underline">
            #{entry.reversalOfEntryId}
          </Link>
        </div>
      )}

      <div className="card p-5 mb-4">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-[13px]">
          <div>
            <p className="text-[var(--sub)] mb-1">{t("journalEntry.entryDate")}</p>
            <p className="text-[var(--ink)] font-bold">{entry.entryDate}</p>
          </div>
          <div>
            <p className="text-[var(--sub)] mb-1">{t("journalEntry.createdBy")}</p>
            <p className="text-[var(--ink)] font-bold">{entry.createdByName}</p>
          </div>
          <div>
            <p className="text-[var(--sub)] mb-1">{t("journalEntry.approvedBy")}</p>
            <p className="text-[var(--ink)] font-bold">{entry.approvedByName || "—"}</p>
          </div>
          <div>
            <p className="text-[var(--sub)] mb-1">{t("journalEntry.source")}</p>
            <p className="text-[var(--ink)] font-bold">{entry.isAutoGenerated ? t("journalEntry.auto") : t("journalEntry.manual")}</p>
          </div>
        </div>
        {entry.description && (
          <div className="mt-4 pt-4 border-t border-[var(--border)]">
            <p className="text-[var(--sub)] mb-1 text-[13px]">{t("journalEntry.description")}</p>
            <p className="text-[var(--ink)] text-[13.5px]">{entry.description}</p>
          </div>
        )}
      </div>

      <div className="card overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-[var(--gold-soft)]/40 border-b border-[var(--border)]">
              <tr>
                <th className="text-right p-3 font-bold text-[var(--gold-deep)] text-[12.5px]">{t("journalEntry.account")}</th>
                <th className="text-right p-3 font-bold text-[var(--gold-deep)] text-[12.5px]">{t("journalEntry.lineDescription")}</th>
                <th className="text-right p-3 font-bold text-[var(--gold-deep)] text-[12.5px]">{t("journalEntry.debit")}</th>
                <th className="text-right p-3 font-bold text-[var(--gold-deep)] text-[12.5px]">{t("journalEntry.credit")}</th>
              </tr>
            </thead>
            <tbody>
              {entry.lines.map((line) => (
                <tr key={line.id} className="border-b border-[var(--border)]">
                  <td className="p-3 text-[var(--ink)]">
                    <span className="text-[var(--sub)]" dir="ltr">
                      {line.accountCode}
                    </span>{" "}
                    {line.accountNameAr}
                  </td>
                  <td className="p-3 text-[var(--sub)]">{line.lineDescription || "—"}</td>
                  <td className="p-3 text-[var(--ink)]" dir="ltr">
                    {line.debit > 0 ? line.debit.toLocaleString("ar-SA") : "—"}
                  </td>
                  <td className="p-3 text-[var(--ink)]" dir="ltr">
                    {line.credit > 0 ? line.credit.toLocaleString("ar-SA") : "—"}
                  </td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr className="bg-[#FAFBFC] font-bold">
                <td colSpan={2} className="p-3 text-[var(--ink)] text-[13px]">
                  {t("journalEntry.total")}
                </td>
                <td className="p-3 text-[var(--ink)]" dir="ltr">
                  {entry.totalDebit.toLocaleString("ar-SA")}
                </td>
                <td className="p-3 text-[var(--ink)]" dir="ltr">
                  {entry.totalCredit.toLocaleString("ar-SA")}
                </td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  );
}
