"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useTranslation } from "react-i18next";
import "@/lib/i18n/config";
import api from "@/lib/api";
import { usePackageFeature } from "@/lib/usePackageFeatures";
import Icon from "@/components/Icon";
import PageHeader from "@/components/PageHeader";
import LoadingState from "@/components/LoadingState";
import RestrictedFeatureState from "@/components/RestrictedFeatureState";
import Can from "@/components/Can";

interface JournalEntry {
  id: number;
  entryNumber: string;
  entryDate: string;
  description: string | null;
  status: string;
  createdByName: string;
  approvedByName: string | null;
  isAutoGenerated: boolean;
  sourceType: string | null;
  totalDebit: number;
  totalCredit: number;
}

const statusLabels: Record<string, string> = {
  PendingApproval: "journalEntry.statusPending",
  Approved: "journalEntry.statusApproved",
  Rejected: "journalEntry.statusRejected",
  Reversed: "journalEntry.statusReversed",
};

const statusStyles: Record<string, string> = {
  PendingApproval: "badge badge--yellow",
  Approved: "badge badge--green",
  Rejected: "badge badge--red",
  Reversed: "badge badge--gray",
};

export default function JournalEntriesPage() {
  const { t } = useTranslation();
  const gate = usePackageFeature("hasAccountingFull");
  const [entries, setEntries] = useState<JournalEntry[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [status, setStatus] = useState("");
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");

  const fetchData = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const params: Record<string, string> = {};
      if (status) params.status = status;
      if (from) params.from = from;
      if (to) params.to = to;
      const res = await api.get("/journal-entries", { params });
      setEntries(res.data.data);
    } catch (err: any) {
      setError(err.response?.data?.message || t("journalEntry.loadError"));
    } finally {
      setLoading(false);
    }
  }, [status, from, to, t]);

  useEffect(() => {
    if (!gate.ready || !gate.allowed) return;
    fetchData();
  }, [fetchData, gate.ready, gate.allowed]);

  if (!gate.ready) {
    return <LoadingState />;
  }

  if (!gate.allowed) {
    return <RestrictedFeatureState />;
  }

  return (
    <div>
      <PageHeader icon="journal" title={t("journalEntry.title")}>
        <Can code="JournalEntries.Add">
          <Link href="/dashboard/accounting/journal-entries/new" className="btn btn-primary">
            <Icon name="plus" />
            {t("journalEntry.newEntry")}
          </Link>
        </Can>
      </PageHeader>

      {error && <div className="alert alert--danger mb-4">{error}</div>}

      <div className="flex flex-wrap items-end gap-3 mb-4">
        <div>
          <label className="block text-[12px] font-bold text-[var(--ink)] mb-1.5">{t("journalEntry.status")}</label>
          <div className="field-shell">
            <select value={status} onChange={(e) => setStatus(e.target.value)}>
              <option value="">{t("common.all")}</option>
              {Object.entries(statusLabels).map(([value, key]) => (
                <option key={value} value={value}>
                  {t(key)}
                </option>
              ))}
            </select>
          </div>
        </div>
        <div>
          <label className="block text-[12px] font-bold text-[var(--ink)] mb-1.5">{t("journalEntry.fromDate")}</label>
          <div className="field-shell">
            <input type="date" value={from} onChange={(e) => setFrom(e.target.value)} />
          </div>
        </div>
        <div>
          <label className="block text-[12px] font-bold text-[var(--ink)] mb-1.5">{t("journalEntry.toDate")}</label>
          <div className="field-shell">
            <input type="date" value={to} onChange={(e) => setTo(e.target.value)} />
          </div>
        </div>
        {(status || from || to) && (
          <button
            onClick={() => {
              setStatus("");
              setFrom("");
              setTo("");
            }}
            className="text-[12.5px] text-[var(--blue)] hover:underline mb-2"
          >
            {t("journalEntry.clearFilters")}
          </button>
        )}
      </div>

      <div className="card overflow-hidden">
        {loading ? (
          <LoadingState />
        ) : entries.length === 0 ? (
          <p className="p-6 text-[var(--sub)] text-sm">{t("journalEntry.noEntries")}</p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead className="bg-[var(--gold-soft)]/40 border-b border-[var(--border)]">
                <tr>
                  <th className="text-right p-4 font-bold text-[var(--gold-deep)] text-[12.5px]">{t("journalEntry.number")}</th>
                  <th className="text-right p-4 font-bold text-[var(--gold-deep)] text-[12.5px]">{t("journalEntry.date")}</th>
                  <th className="text-right p-4 font-bold text-[var(--gold-deep)] text-[12.5px]">{t("journalEntry.description")}</th>
                  <th className="text-right p-4 font-bold text-[var(--gold-deep)] text-[12.5px]">{t("journalEntry.total")}</th>
                  <th className="text-right p-4 font-bold text-[var(--gold-deep)] text-[12.5px]">{t("journalEntry.createdBy")}</th>
                  <th className="text-right p-4 font-bold text-[var(--gold-deep)] text-[12.5px]">{t("journalEntry.status")}</th>
                </tr>
              </thead>
              <tbody>
                {entries.map((entry) => (
                  <tr
                    key={entry.id}
                    className="border-b border-[var(--border)] hover:bg-[var(--blue-50)]/40 transition-colors cursor-pointer"
                  >
                    <td className="p-4">
                      <Link
                        href={`/dashboard/accounting/journal-entries/${entry.id}`}
                        className="text-[var(--blue)] font-bold hover:underline"
                        dir="ltr"
                      >
                        {entry.entryNumber}
                      </Link>
                    </td>
                    <td className="p-4 text-[var(--ink)]">{entry.entryDate}</td>
                    <td className="p-4 text-[var(--sub)] max-w-xs truncate">{entry.description || "—"}</td>
                    <td className="p-4 text-[var(--ink)]" dir="ltr">
                      {entry.totalDebit.toLocaleString("ar-SA-u-nu-latn")} {t("common.sar")}
                    </td>
                    <td className="p-4 text-[var(--sub)]">{entry.createdByName}</td>
                    <td className="p-4">
                      <span className={statusStyles[entry.status] ?? "badge badge--gray"}>
                        {t(statusLabels[entry.status] ?? "common.noData")}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
