using FatooraRahatak.Domain.Common;
using FatooraRahatak.Domain.Enums;
using FatooraRahatak.Domain.Entities.Stores;
using FatooraRahatak.Domain.Entities.Users;

namespace FatooraRahatak.Domain.Entities.Accounting;

// قيد يومية — رأس القيد (السطور الفعلية في JournalEntryLine)
public class JournalEntry : BaseEntity
{
    public long StoreId { get; set; }
    public string EntryNumber { get; set; } = string.Empty; // فريد داخل المتجر، مُولَّد تلقائيًا
    public DateOnly EntryDate { get; set; }
    public string? Description { get; set; }
    public JournalEntryStatus Status { get; set; } = JournalEntryStatus.PendingApproval;
    public long CreatedByUserId { get; set; }
    public long? ApprovedByUserId { get; set; }
    public long? ReversalOfEntryId { get; set; } // لو هذا القيد عكسي، يشير للقيد الأصلي
    public bool IsAutoGenerated { get; set; } = false;
    public JournalSourceType? SourceType { get; set; }

    public Store Store { get; set; } = null!;
    public User CreatedBy { get; set; } = null!;
    public User? ApprovedBy { get; set; }
    public JournalEntry? ReversalOfEntry { get; set; }
    public ICollection<JournalEntryLine> Lines { get; set; } = new List<JournalEntryLine>();
}